spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_account
    username: root
    password: lgh123
    driver-class-name: com.mysql.cj.jdbc.Driver

#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource

    druid:
      aop-patterns: com.example.webadmin.*  #监控SpringBean
      filters: stat,wall  # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: 12345
        reset-enable: false

      web-stat-filter:   # 监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter: # 对上面filters里面的stat的详细配置
        stat:
          slow-sql-millis: 1000  #单位：毫秒
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false  #拦截所有删表的操作
  #            update-allow: false #更新操作都会被拦截
  jdbc:
    template:
      query-timeout: 3  #秒为单位
# 配置mybatis的规则
mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml   # 全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml    # sql映射文件位置
#  configuration: # 指定mybatis全局配置文件中的相关配置项
#    map-underscore-to-camel-case: true